// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deposit.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const approveDeposits = `-- name: ApproveDeposits :exec
UPDATE user_deposits SET "status" = 'Approved' WHERE id = $1
`

func (q *Queries) ApproveDeposits(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, approveDeposits, id)
	return err
}

const createNewDeposit = `-- name: CreateNewDeposit :exec
INSERT INTO user_deposits(user_id, amount, transaction_id, deposit_proof) VALUES($1, $2, $3, $4)
`

type CreateNewDepositParams struct {
	UserID        uuid.UUID
	Amount        decimal.Decimal
	TransactionID string
	DepositProof  string
}

func (q *Queries) CreateNewDeposit(ctx context.Context, arg CreateNewDepositParams) error {
	_, err := q.db.ExecContext(ctx, createNewDeposit,
		arg.UserID,
		arg.Amount,
		arg.TransactionID,
		arg.DepositProof,
	)
	return err
}

const declineDeposit = `-- name: DeclineDeposit :exec
UPDATE user_deposits SET "status" = 'Declined' WHERE id = $1
`

func (q *Queries) DeclineDeposit(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, declineDeposit, id)
	return err
}

const getAllDeposits = `-- name: GetAllDeposits :many
SELECT 
    d.id, d.user_id, d.status, d.amount, d.transaction_id, d.deposit_proof, d.created_at, 
    u.email,
    u.fullname,
    u.username
FROM user_deposits d
JOIN users u ON d.user_id = u.id
ORDER BY d.created_at DESC
`

type GetAllDepositsRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Status        string
	Amount        decimal.Decimal
	TransactionID string
	DepositProof  string
	CreatedAt     time.Time
	Email         string
	Fullname      string
	Username      string
}

func (q *Queries) GetAllDeposits(ctx context.Context) ([]GetAllDepositsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllDeposits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllDepositsRow
	for rows.Next() {
		var i GetAllDepositsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Amount,
			&i.TransactionID,
			&i.DepositProof,
			&i.CreatedAt,
			&i.Email,
			&i.Fullname,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDepositsByUserId = `-- name: GetAllDepositsByUserId :many
SELECT 
    d.id, d.user_id, d.status, d.amount, d.transaction_id, d.deposit_proof, d.created_at, 
    u.email,
    u.fullname,
    u.username
FROM user_deposits d
JOIN users u ON d.user_id = u.id
WHERE d.user_id = $1
ORDER BY d.created_at DESC
`

type GetAllDepositsByUserIdRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Status        string
	Amount        decimal.Decimal
	TransactionID string
	DepositProof  string
	CreatedAt     time.Time
	Email         string
	Fullname      string
	Username      string
}

func (q *Queries) GetAllDepositsByUserId(ctx context.Context, userID uuid.UUID) ([]GetAllDepositsByUserIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllDepositsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllDepositsByUserIdRow
	for rows.Next() {
		var i GetAllDepositsByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Amount,
			&i.TransactionID,
			&i.DepositProof,
			&i.CreatedAt,
			&i.Email,
			&i.Fullname,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPendingDeposit = `-- name: GetAllPendingDeposit :many
SELECT 
    d.id, d.user_id, d.status, d.amount, d.transaction_id, d.deposit_proof, d.created_at, 
    u.email,
    u.fullname,
    u.username
FROM user_deposits d
JOIN users u ON d.user_id = u.id
WHERE "status" = 'Pending'
ORDER BY d.created_at DESC
`

type GetAllPendingDepositRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Status        string
	Amount        decimal.Decimal
	TransactionID string
	DepositProof  string
	CreatedAt     time.Time
	Email         string
	Fullname      string
	Username      string
}

func (q *Queries) GetAllPendingDeposit(ctx context.Context) ([]GetAllPendingDepositRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPendingDeposit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPendingDepositRow
	for rows.Next() {
		var i GetAllPendingDepositRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Amount,
			&i.TransactionID,
			&i.DepositProof,
			&i.CreatedAt,
			&i.Email,
			&i.Fullname,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPendingDepositByUserID = `-- name: GetAllPendingDepositByUserID :many
SELECT 
    d.id, d.user_id, d.status, d.amount, d.transaction_id, d.deposit_proof, d.created_at, 
    u.email,
    u.fullname,
    u.username
FROM user_deposits d
JOIN users u ON d.user_id = u.id
WHERE d.status = 'Pending'
  AND d.user_id = $1
ORDER BY d.created_at DESC
`

type GetAllPendingDepositByUserIDRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Status        string
	Amount        decimal.Decimal
	TransactionID string
	DepositProof  string
	CreatedAt     time.Time
	Email         string
	Fullname      string
	Username      string
}

func (q *Queries) GetAllPendingDepositByUserID(ctx context.Context, userID uuid.UUID) ([]GetAllPendingDepositByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPendingDepositByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPendingDepositByUserIDRow
	for rows.Next() {
		var i GetAllPendingDepositByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Amount,
			&i.TransactionID,
			&i.DepositProof,
			&i.CreatedAt,
			&i.Email,
			&i.Fullname,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDepositByID = `-- name: GetDepositByID :one
SELECT id, user_id, status, amount, transaction_id, deposit_proof, created_at FROM user_deposits WHERE id = $1
`

func (q *Queries) GetDepositByID(ctx context.Context, id uuid.UUID) (UserDeposit, error) {
	row := q.db.QueryRowContext(ctx, getDepositByID, id)
	var i UserDeposit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Amount,
		&i.TransactionID,
		&i.DepositProof,
		&i.CreatedAt,
	)
	return i, err
}

const sumAllDepositAmountByUserID = `-- name: SumAllDepositAmountByUserID :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC(18,6) AS total_deposited FROM user_deposits WHERE "status" = 'Approved' AND id = $1
`

func (q *Queries) SumAllDepositAmountByUserID(ctx context.Context, id uuid.UUID) (decimal.Decimal, error) {
	row := q.db.QueryRowContext(ctx, sumAllDepositAmountByUserID, id)
	var total_deposited decimal.Decimal
	err := row.Scan(&total_deposited)
	return total_deposited, err
}

const sumApprovedDeposits = `-- name: SumApprovedDeposits :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC(18,6) AS total_deposited FROM user_deposits WHERE "status" = 'Approved'
`

func (q *Queries) SumApprovedDeposits(ctx context.Context) (decimal.Decimal, error) {
	row := q.db.QueryRowContext(ctx, sumApprovedDeposits)
	var total_deposited decimal.Decimal
	err := row.Scan(&total_deposited)
	return total_deposited, err
}
