// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: investment.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createInv = `-- name: CreateInv :exec
INSERT INTO investments(user_id, plan_id, amount, end_date, expected_profit)
VALUES
($1, $2, $3, $4, $5)
`

type CreateInvParams struct {
	UserID         uuid.UUID
	PlanID         uuid.UUID
	Amount         decimal.Decimal
	EndDate        time.Time
	ExpectedProfit decimal.Decimal
}

func (q *Queries) CreateInv(ctx context.Context, arg CreateInvParams) error {
	_, err := q.db.ExecContext(ctx, createInv,
		arg.UserID,
		arg.PlanID,
		arg.Amount,
		arg.EndDate,
		arg.ExpectedProfit,
	)
	return err
}

const getActiveInvByUserId = `-- name: GetActiveInvByUserId :many
SELECT id, user_id, plan_id, amount, start_date, end_date, expected_profit, status, created_at FROM investments WHERE id = $1 AND "status" = 'Ongoing' ORDER BY created_at DESC
`

func (q *Queries) GetActiveInvByUserId(ctx context.Context, id uuid.UUID) ([]Investment, error) {
	rows, err := q.db.QueryContext(ctx, getActiveInvByUserId, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Investment
	for rows.Next() {
		var i Investment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Amount,
			&i.StartDate,
			&i.EndDate,
			&i.ExpectedProfit,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllActiveInv = `-- name: GetAllActiveInv :many
SELECT 
    d.id, d.user_id, d.plan_id, d.amount, d.start_date, d.end_date, d.expected_profit, d.status, d.created_at,
    u.email,
    u.fullname,
    u.username
FROM investments d 
JOIN users u ON d.user_id = u.id
WHERE "status" = 'Ongoing' ORDER BY d.created_at DESC
`

type GetAllActiveInvRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	PlanID         uuid.UUID
	Amount         decimal.Decimal
	StartDate      time.Time
	EndDate        time.Time
	ExpectedProfit decimal.Decimal
	Status         string
	CreatedAt      time.Time
	Email          string
	Fullname       string
	Username       string
}

func (q *Queries) GetAllActiveInv(ctx context.Context) ([]GetAllActiveInvRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllActiveInv)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllActiveInvRow
	for rows.Next() {
		var i GetAllActiveInvRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Amount,
			&i.StartDate,
			&i.EndDate,
			&i.ExpectedProfit,
			&i.Status,
			&i.CreatedAt,
			&i.Email,
			&i.Fullname,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllInvByUserId = `-- name: GetAllInvByUserId :many
SELECT id, user_id, plan_id, amount, start_date, end_date, expected_profit, status, created_at FROM investments WHERE id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetAllInvByUserId(ctx context.Context, id uuid.UUID) ([]Investment, error) {
	rows, err := q.db.QueryContext(ctx, getAllInvByUserId, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Investment
	for rows.Next() {
		var i Investment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Amount,
			&i.StartDate,
			&i.EndDate,
			&i.ExpectedProfit,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
