// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kyc.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const approvekyc = `-- name: Approvekyc :exec
UPDATE user_kycs SET "status" = 'Approved' WHERE id = $1
`

func (q *Queries) Approvekyc(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, approvekyc, id)
	return err
}

const declinekyc = `-- name: Declinekyc :exec
UPDATE user_kycs SET "status" = 'Declined' WHERE id = $1
`

func (q *Queries) Declinekyc(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, declinekyc, id)
	return err
}

const getAllKyc = `-- name: GetAllKyc :many
SELECT 
    d.id, d.user_id, d.status, d.id_image_front, d.id_image_back, d.created_at,
    u.username,
    u.email,
    u.fullname
FROM user_kycs d
JOIN users u ON d.user_id = u.id ORDER BY d.created_at DESC
`

type GetAllKycRow struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Status       string
	IDImageFront string
	IDImageBack  string
	CreatedAt    time.Time
	Username     string
	Email        string
	Fullname     string
}

func (q *Queries) GetAllKyc(ctx context.Context) ([]GetAllKycRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllKyc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllKycRow
	for rows.Next() {
		var i GetAllKycRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.IDImageFront,
			&i.IDImageBack,
			&i.CreatedAt,
			&i.Username,
			&i.Email,
			&i.Fullname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPendingKyc = `-- name: GetAllPendingKyc :many
SELECT 
    d.id, d.user_id, d.status, d.id_image_front, d.id_image_back, d.created_at,
    u.username,
    u.email,
    u.fullname
FROM user_kycs d
JOIN users u ON d.user_id = u.id 
WHERE "status" = 'Pending'
ORDER BY d.created_at DESC
`

type GetAllPendingKycRow struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Status       string
	IDImageFront string
	IDImageBack  string
	CreatedAt    time.Time
	Username     string
	Email        string
	Fullname     string
}

func (q *Queries) GetAllPendingKyc(ctx context.Context) ([]GetAllPendingKycRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPendingKyc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPendingKycRow
	for rows.Next() {
		var i GetAllPendingKycRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.IDImageFront,
			&i.IDImageBack,
			&i.CreatedAt,
			&i.Username,
			&i.Email,
			&i.Fullname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKycById = `-- name: GetKycById :one
SELECT id, user_id, status, id_image_front, id_image_back, created_at FROM user_kycs WHERE id = $1
`

func (q *Queries) GetKycById(ctx context.Context, id uuid.UUID) (UserKyc, error) {
	row := q.db.QueryRowContext(ctx, getKycById, id)
	var i UserKyc
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.IDImageFront,
		&i.IDImageBack,
		&i.CreatedAt,
	)
	return i, err
}

const savekyc = `-- name: Savekyc :exec
INSERT INTO user_kycs(user_id, id_image_front, id_image_back) VALUES ($1, $2, $3)
`

type SavekycParams struct {
	UserID       uuid.UUID
	IDImageFront string
	IDImageBack  string
}

func (q *Queries) Savekyc(ctx context.Context, arg SavekycParams) error {
	_, err := q.db.ExecContext(ctx, savekyc, arg.UserID, arg.IDImageFront, arg.IDImageBack)
	return err
}
