// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type AdminWalletAddress struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Coin        string
	CoinLogo    string
	Address     string
	QrCode      string
	NetworkType string
	CreatedAt   time.Time
}

type Investment struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	PlanID         uuid.UUID
	Amount         decimal.Decimal
	StartDate      time.Time
	EndDate        time.Time
	ExpectedProfit decimal.Decimal
	Status         string
	CreatedAt      time.Time
}

type Plan struct {
	ID           uuid.UUID
	Name         string
	MinAmount    decimal.Decimal
	MaxAmount    decimal.Decimal
	DurationDays int32
	Roi          decimal.Decimal
	CreatedAt    time.Time
}

type User struct {
	ID             uuid.UUID
	Email          string
	Role           string
	Fullname       string
	Username       string
	Gender         string
	Country        string
	PhoneNumber    string
	WalletBalance  decimal.Decimal
	ProfitBalance  decimal.Decimal
	InvestedAmount decimal.Decimal
	ReferalBonus   decimal.Decimal
	ReferalLink    string
	Verified       bool
	Status         string
	Password       string
	CreatedAt      time.Time
}

type UserDeposit struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Status        string
	Amount        decimal.Decimal
	TransactionID string
	DepositProof  string
	CreatedAt     time.Time
}

type UserKyc struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Status       string
	IDImageFront string
	IDImageBack  string
	CreatedAt    time.Time
}

type UserPasswordReset struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type UserWalletAddress struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	BtcBtcAddress    sql.NullString
	BtcBep20Address  sql.NullString
	EthErc20Address  sql.NullString
	EthBep20Address  sql.NullString
	UsdtTrc20Address sql.NullString
	UsdtBep20Address sql.NullString
	CreatedAt        time.Time
}

type UserWithdrawal struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Status        string
	Amount        decimal.Decimal
	TransactionID string
	CoinType      string
	WalletAddress string
	CreatedAt     time.Time
}
