// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createPlan = `-- name: CreatePlan :exec
INSERT INTO plans("name", min_amount, max_amount, duration_days, roi) VALUES($1, $2, $3, $4, $5)
`

type CreatePlanParams struct {
	Name         string
	MinAmount    decimal.Decimal
	MaxAmount    decimal.Decimal
	DurationDays int32
	Roi          decimal.Decimal
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) error {
	_, err := q.db.ExecContext(ctx, createPlan,
		arg.Name,
		arg.MinAmount,
		arg.MaxAmount,
		arg.DurationDays,
		arg.Roi,
	)
	return err
}

const deletePlanById = `-- name: DeletePlanById :exec
DELETE FROM plans WHERE id = $1
`

func (q *Queries) DeletePlanById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePlanById, id)
	return err
}

const fetchAllPlans = `-- name: FetchAllPlans :many
SELECT id, name, min_amount, max_amount, duration_days, roi, created_at FROM plans
`

func (q *Queries) FetchAllPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.QueryContext(ctx, fetchAllPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MinAmount,
			&i.MaxAmount,
			&i.DurationDays,
			&i.Roi,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, name, min_amount, max_amount, duration_days, roi, created_at FROM plans WHERE id = $1
`

func (q *Queries) GetPlanByID(ctx context.Context, id uuid.UUID) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MinAmount,
		&i.MaxAmount,
		&i.DurationDays,
		&i.Roi,
		&i.CreatedAt,
	)
	return i, err
}
