// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Querier interface {
	AddAdminWalletAddress(ctx context.Context, arg AddAdminWalletAddressParams) error
	AdminExists(ctx context.Context) (int64, error)
	ApproveDeposits(ctx context.Context, id uuid.UUID) error
	ApproveWithdrawal(ctx context.Context, userID uuid.UUID) error
	Approvekyc(ctx context.Context, id uuid.UUID) error
	CountUsers(ctx context.Context) (int64, error)
	CreateInv(ctx context.Context, arg CreateInvParams) error
	CreateNewDeposit(ctx context.Context, arg CreateNewDepositParams) error
	CreateNewWithdrawal(ctx context.Context, arg CreateNewWithdrawalParams) error
	CreatePlan(ctx context.Context, arg CreatePlanParams) error
	CreateResetToken(ctx context.Context, arg CreateResetTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeclineDeposit(ctx context.Context, id uuid.UUID) error
	DeclineWithdrawal(ctx context.Context, userID uuid.UUID) error
	Declinekyc(ctx context.Context, id uuid.UUID) error
	DeletePlanById(ctx context.Context, id uuid.UUID) error
	DeleteTokenByID(ctx context.Context, id uuid.UUID) error
	DeleteUserById(ctx context.Context, id uuid.UUID) error
	DeleteWalletAddressByID(ctx context.Context, id uuid.UUID) error
	FetchAllPlans(ctx context.Context) ([]Plan, error)
	GetActiveInvByUserId(ctx context.Context, id uuid.UUID) ([]Investment, error)
	GetAdminWalletAddress(ctx context.Context) ([]AdminWalletAddress, error)
	GetAllActiveInv(ctx context.Context) ([]GetAllActiveInvRow, error)
	GetAllDeposits(ctx context.Context) ([]GetAllDepositsRow, error)
	GetAllDepositsByUserId(ctx context.Context, userID uuid.UUID) ([]GetAllDepositsByUserIdRow, error)
	GetAllInvByUserId(ctx context.Context, id uuid.UUID) ([]Investment, error)
	GetAllKyc(ctx context.Context) ([]GetAllKycRow, error)
	GetAllPendingDeposit(ctx context.Context) ([]GetAllPendingDepositRow, error)
	GetAllPendingDepositByUserID(ctx context.Context, userID uuid.UUID) ([]GetAllPendingDepositByUserIDRow, error)
	GetAllPendingKyc(ctx context.Context) ([]GetAllPendingKycRow, error)
	GetAllPendingWithdrawal(ctx context.Context) ([]GetAllPendingWithdrawalRow, error)
	GetAllPendingWithdrawalByID(ctx context.Context, userID uuid.UUID) ([]UserWithdrawal, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetAllWithdrawal(ctx context.Context) ([]GetAllWithdrawalRow, error)
	GetAllWithdrawalByUserId(ctx context.Context, userID uuid.UUID) ([]UserWithdrawal, error)
	GetDepositByID(ctx context.Context, id uuid.UUID) (UserDeposit, error)
	GetKycById(ctx context.Context, id uuid.UUID) (UserKyc, error)
	GetPlanByID(ctx context.Context, id uuid.UUID) (Plan, error)
	GetTokenById(ctx context.Context, token string) (UserPasswordReset, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetWithdrawalById(ctx context.Context, id uuid.UUID) (GetWithdrawalByIdRow, error)
	Savekyc(ctx context.Context, arg SavekycParams) error
	SumAllDepositAmountByUserID(ctx context.Context, id uuid.UUID) (decimal.Decimal, error)
	SumAllWithdrawalAmountByUserID(ctx context.Context, userID uuid.UUID) (decimal.Decimal, error)
	SumApprovedDeposits(ctx context.Context) (decimal.Decimal, error)
	SumApprovedWithdrawals(ctx context.Context) (decimal.Decimal, error)
	UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) error
	UpdateKycStatus(ctx context.Context, id uuid.UUID) error
	UpdateUserAcc(ctx context.Context, arg UpdateUserAccParams) error
	UpdateUserBalanceByID(ctx context.Context, arg UpdateUserBalanceByIDParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
