// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_password_reset.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createResetToken = `-- name: CreateResetToken :exec
INSERT INTO user_password_resets(user_id, token, expires_at) VALUES($1, $2, $3)
`

type CreateResetTokenParams struct {
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
}

func (q *Queries) CreateResetToken(ctx context.Context, arg CreateResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, createResetToken, arg.UserID, arg.Token, arg.ExpiresAt)
	return err
}

const deleteTokenByID = `-- name: DeleteTokenByID :exec
DELETE FROM user_password_resets WHERE id = $1
`

func (q *Queries) DeleteTokenByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTokenByID, id)
	return err
}

const getTokenById = `-- name: GetTokenById :one
SELECT id, user_id, token, expires_at, created_at FROM user_password_resets WHERE token = $1
`

func (q *Queries) GetTokenById(ctx context.Context, token string) (UserPasswordReset, error) {
	row := q.db.QueryRowContext(ctx, getTokenById, token)
	var i UserPasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
