// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const adminExists = `-- name: AdminExists :one
SELECT COUNT(*) FROM users WHERE "role" = 'admin'
`

func (q *Queries) AdminExists(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminExists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users WHERE "role" = 'user'
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (email, "role", fullname, username, gender, country, phone_number, referal_link, password) 
VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateUserParams struct {
	Email       string
	Role        string
	Fullname    string
	Username    string
	Gender      string
	Country     string
	PhoneNumber string
	ReferalLink string
	Password    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.Email,
		arg.Role,
		arg.Fullname,
		arg.Username,
		arg.Gender,
		arg.Country,
		arg.PhoneNumber,
		arg.ReferalLink,
		arg.Password,
	)
	return err
}

const deleteUserById = `-- name: DeleteUserById :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUserById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserById, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, email, role, fullname, username, gender, country, phone_number, wallet_balance, profit_balance, invested_amount, referal_bonus, referal_link, verified, status, password, created_at FROM users WHERE "role" = 'user'
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.Fullname,
			&i.Username,
			&i.Gender,
			&i.Country,
			&i.PhoneNumber,
			&i.WalletBalance,
			&i.ProfitBalance,
			&i.InvestedAmount,
			&i.ReferalBonus,
			&i.ReferalLink,
			&i.Verified,
			&i.Status,
			&i.Password,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, role, fullname, username, gender, country, phone_number, wallet_balance, profit_balance, invested_amount, referal_bonus, referal_link, verified, status, password, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Fullname,
		&i.Username,
		&i.Gender,
		&i.Country,
		&i.PhoneNumber,
		&i.WalletBalance,
		&i.ProfitBalance,
		&i.InvestedAmount,
		&i.ReferalBonus,
		&i.ReferalLink,
		&i.Verified,
		&i.Status,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, role, fullname, username, gender, country, phone_number, wallet_balance, profit_balance, invested_amount, referal_bonus, referal_link, verified, status, password, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Fullname,
		&i.Username,
		&i.Gender,
		&i.Country,
		&i.PhoneNumber,
		&i.WalletBalance,
		&i.ProfitBalance,
		&i.InvestedAmount,
		&i.ReferalBonus,
		&i.ReferalLink,
		&i.Verified,
		&i.Status,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :exec
UPDATE users SET status = $1 WHERE id = $2
`

type UpdateAccountStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountStatus, arg.Status, arg.ID)
	return err
}

const updateKycStatus = `-- name: UpdateKycStatus :exec
UPDATE users SET verified = 'TRUE' WHERE id = $1
`

func (q *Queries) UpdateKycStatus(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateKycStatus, id)
	return err
}

const updateUserAcc = `-- name: UpdateUserAcc :exec
UPDATE users SET wallet_balance = $1, profit_balance = $2, invested_amount = $3, referal_bonus = $4 WHERE id = $5
`

type UpdateUserAccParams struct {
	WalletBalance  decimal.Decimal
	ProfitBalance  decimal.Decimal
	InvestedAmount decimal.Decimal
	ReferalBonus   decimal.Decimal
	ID             uuid.UUID
}

func (q *Queries) UpdateUserAcc(ctx context.Context, arg UpdateUserAccParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAcc,
		arg.WalletBalance,
		arg.ProfitBalance,
		arg.InvestedAmount,
		arg.ReferalBonus,
		arg.ID,
	)
	return err
}

const updateUserBalanceByID = `-- name: UpdateUserBalanceByID :exec
UPDATE users SET wallet_balance = $1 WHERE id = $2
`

type UpdateUserBalanceByIDParams struct {
	WalletBalance decimal.Decimal
	ID            uuid.UUID
}

func (q *Queries) UpdateUserBalanceByID(ctx context.Context, arg UpdateUserBalanceByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateUserBalanceByID, arg.WalletBalance, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password = $1 WHERE id = $2
`

type UpdateUserPasswordParams struct {
	Password string
	ID       uuid.UUID
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.Password, arg.ID)
	return err
}
