// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallet_address.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addAdminWalletAddress = `-- name: AddAdminWalletAddress :exec
INSERT INTO admin_wallet_addresses(user_id, coin, coin_logo, "address", qr_code, network_type) VALUES($1, $2, $3, $4, $5, $6)
`

type AddAdminWalletAddressParams struct {
	UserID      uuid.UUID
	Coin        string
	CoinLogo    string
	Address     string
	QrCode      string
	NetworkType string
}

func (q *Queries) AddAdminWalletAddress(ctx context.Context, arg AddAdminWalletAddressParams) error {
	_, err := q.db.ExecContext(ctx, addAdminWalletAddress,
		arg.UserID,
		arg.Coin,
		arg.CoinLogo,
		arg.Address,
		arg.QrCode,
		arg.NetworkType,
	)
	return err
}

const deleteWalletAddressByID = `-- name: DeleteWalletAddressByID :exec
DELETE FROM admin_wallet_addresses WHERE id = $1
`

func (q *Queries) DeleteWalletAddressByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWalletAddressByID, id)
	return err
}

const getAdminWalletAddress = `-- name: GetAdminWalletAddress :many
SELECT id, user_id, coin, coin_logo, address, qr_code, network_type, created_at FROM admin_wallet_addresses
`

func (q *Queries) GetAdminWalletAddress(ctx context.Context) ([]AdminWalletAddress, error) {
	rows, err := q.db.QueryContext(ctx, getAdminWalletAddress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminWalletAddress
	for rows.Next() {
		var i AdminWalletAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Coin,
			&i.CoinLogo,
			&i.Address,
			&i.QrCode,
			&i.NetworkType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
