// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: withdrawal.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const approveWithdrawal = `-- name: ApproveWithdrawal :exec
UPDATE user_withdrawals SET "status" = 'Approved' WHERE user_id = $1
`

func (q *Queries) ApproveWithdrawal(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, approveWithdrawal, userID)
	return err
}

const createNewWithdrawal = `-- name: CreateNewWithdrawal :exec
INSERT INTO user_withdrawals(user_id, amount, transaction_id, coin_type, wallet_address) VALUES($1, $2, $3, $4, $5)
`

type CreateNewWithdrawalParams struct {
	UserID        uuid.UUID
	Amount        decimal.Decimal
	TransactionID string
	CoinType      string
	WalletAddress string
}

func (q *Queries) CreateNewWithdrawal(ctx context.Context, arg CreateNewWithdrawalParams) error {
	_, err := q.db.ExecContext(ctx, createNewWithdrawal,
		arg.UserID,
		arg.Amount,
		arg.TransactionID,
		arg.CoinType,
		arg.WalletAddress,
	)
	return err
}

const declineWithdrawal = `-- name: DeclineWithdrawal :exec
UPDATE user_withdrawals SET "status" = 'Declined' WHERE user_id = $1
`

func (q *Queries) DeclineWithdrawal(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, declineWithdrawal, userID)
	return err
}

const getAllPendingWithdrawal = `-- name: GetAllPendingWithdrawal :many
SELECT d.id, d.user_id, d.status, d.amount, d.transaction_id, d.coin_type, d.wallet_address, d.created_at,
        u.username,
        u.email,
        u.fullname
FROM user_withdrawals d 
JOIN users u ON d.user_id = u.id WHERE d."status" = 'Pending'
`

type GetAllPendingWithdrawalRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Status        string
	Amount        decimal.Decimal
	TransactionID string
	CoinType      string
	WalletAddress string
	CreatedAt     time.Time
	Username      string
	Email         string
	Fullname      string
}

func (q *Queries) GetAllPendingWithdrawal(ctx context.Context) ([]GetAllPendingWithdrawalRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPendingWithdrawal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPendingWithdrawalRow
	for rows.Next() {
		var i GetAllPendingWithdrawalRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Amount,
			&i.TransactionID,
			&i.CoinType,
			&i.WalletAddress,
			&i.CreatedAt,
			&i.Username,
			&i.Email,
			&i.Fullname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPendingWithdrawalByID = `-- name: GetAllPendingWithdrawalByID :many
SELECT id, user_id, status, amount, transaction_id, coin_type, wallet_address, created_at FROM user_withdrawals WHERE "status" = 'Pending' AND user_id = $1
`

func (q *Queries) GetAllPendingWithdrawalByID(ctx context.Context, userID uuid.UUID) ([]UserWithdrawal, error) {
	rows, err := q.db.QueryContext(ctx, getAllPendingWithdrawalByID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserWithdrawal
	for rows.Next() {
		var i UserWithdrawal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Amount,
			&i.TransactionID,
			&i.CoinType,
			&i.WalletAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllWithdrawal = `-- name: GetAllWithdrawal :many
SELECT d.id, d.user_id, d.status, d.amount, d.transaction_id, d.coin_type, d.wallet_address, d.created_at,
        u.username,
        u.email,
        u.fullname
FROM user_withdrawals d
JOIN users u ON d.user_id = u.id ORDER BY d.created_at DESC
`

type GetAllWithdrawalRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Status        string
	Amount        decimal.Decimal
	TransactionID string
	CoinType      string
	WalletAddress string
	CreatedAt     time.Time
	Username      string
	Email         string
	Fullname      string
}

func (q *Queries) GetAllWithdrawal(ctx context.Context) ([]GetAllWithdrawalRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllWithdrawal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllWithdrawalRow
	for rows.Next() {
		var i GetAllWithdrawalRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Amount,
			&i.TransactionID,
			&i.CoinType,
			&i.WalletAddress,
			&i.CreatedAt,
			&i.Username,
			&i.Email,
			&i.Fullname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllWithdrawalByUserId = `-- name: GetAllWithdrawalByUserId :many
SELECT id, user_id, status, amount, transaction_id, coin_type, wallet_address, created_at FROM user_withdrawals WHERE user_id = $1
`

func (q *Queries) GetAllWithdrawalByUserId(ctx context.Context, userID uuid.UUID) ([]UserWithdrawal, error) {
	rows, err := q.db.QueryContext(ctx, getAllWithdrawalByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserWithdrawal
	for rows.Next() {
		var i UserWithdrawal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Amount,
			&i.TransactionID,
			&i.CoinType,
			&i.WalletAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWithdrawalById = `-- name: GetWithdrawalById :one
SELECT d.id, d.user_id, d.status, d.amount, d.transaction_id, d.coin_type, d.wallet_address, d.created_at,
        u.username,
        u.email,
        u.fullname
FROM user_withdrawals d
JOIN users u ON d.user_id = u.id WHERE d.id = $1
`

type GetWithdrawalByIdRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Status        string
	Amount        decimal.Decimal
	TransactionID string
	CoinType      string
	WalletAddress string
	CreatedAt     time.Time
	Username      string
	Email         string
	Fullname      string
}

func (q *Queries) GetWithdrawalById(ctx context.Context, id uuid.UUID) (GetWithdrawalByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getWithdrawalById, id)
	var i GetWithdrawalByIdRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Amount,
		&i.TransactionID,
		&i.CoinType,
		&i.WalletAddress,
		&i.CreatedAt,
		&i.Username,
		&i.Email,
		&i.Fullname,
	)
	return i, err
}

const sumAllWithdrawalAmountByUserID = `-- name: SumAllWithdrawalAmountByUserID :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC(18,6) AS total_withdrawal FROM user_withdrawals WHERE "status" = 'Approved' AND user_id = $1
`

func (q *Queries) SumAllWithdrawalAmountByUserID(ctx context.Context, userID uuid.UUID) (decimal.Decimal, error) {
	row := q.db.QueryRowContext(ctx, sumAllWithdrawalAmountByUserID, userID)
	var total_withdrawal decimal.Decimal
	err := row.Scan(&total_withdrawal)
	return total_withdrawal, err
}

const sumApprovedWithdrawals = `-- name: SumApprovedWithdrawals :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC(18,6) AS total_withdrawal FROM user_withdrawals WHERE "status" = 'Approved'
`

func (q *Queries) SumApprovedWithdrawals(ctx context.Context) (decimal.Decimal, error) {
	row := q.db.QueryRowContext(ctx, sumApprovedWithdrawals)
	var total_withdrawal decimal.Decimal
	err := row.Scan(&total_withdrawal)
	return total_withdrawal, err
}
